#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = pdfviewer
MAIN            = parser.goc obj.goc gfxState.goc gfx.goc page.goc\
                  stream.goc gfxFont.goc lexer.goc pdfEngine.goc array.goc\
                  xref.goc dict.goc catalog.goc
UI              = pdfvu.goc
UTIL            = gmem.goc gstr.goc
UI_TO_RDFS      =
OBJS            = parser.obj obj.obj gfxState.obj gfx.obj page.obj\
                  stream.obj gfxFont.obj lexer.obj pdfEngine.obj array.obj\
                  xref.obj dict.obj catalog.obj pdfvu.obj gmem.obj gstr.obj
COMMON          = pdfEngine.h gmem.goh gtypes.goh gfx.goh stream.goh\
                  obj.goh xref.goh diction.goh page.goh parser.goh\
                  catalog.goh array.goh ccitt.h lexer.goh gfxState.goh\
                  gfxFont.goh gstr.goh pdfGeode.goh pdfvu.goh gfxFont2.goh
MODULES         =
CMODULES        = main ui util
SRCS            = $(MAIN) $(UI) $(UTIL) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
